## ODD Home Work-Week 5- Standardizing and Merging Datas with using dplyr functions

### Install the package if you already haven't
install.packages("tidyverse", repos = "https://cran.r-project.org")
library(tidyverse)

install.packages("readxl")

install.packages("dplyr")
library(dplyr)

install.packages("magrittr")
library(magrittr)

### to be sure there is no temp file due to excess running
file.remove(tmp)

### create temporary file
tmp <-tempfile(fileext=".xlsx")
download.file("https://github.com/MEF-BDA503/pj18-elmasriomer/blob/master/odd_retail_sales_2017_11.XLSX", destfile=tmp)
### read that excel file  using readxl package's read excel function
raw_data <- readxl::read_excel(tmp,skip=7,col_names=FALSE)
file.remove(tmp)
### IT IS WORKING-CHECKED

raw_data <- slice(raw_data, -c(46,47))

### Let us see the head and tail
head(raw_data)
tail(raw_data)

colnames(raw_data) <- c("brand_name","auto_dom","auto_imp","auto_total","comm_dom","comm_imp","comm_total","total_dom","total_imp","total_total")

car_data_nov_17 <- raw_data %>% 
mutate_if(is.numeric,funs(ifelse(is.na(.),0,.))) %>% 
mutate(year=2017,month=11)


print(car_data_nov_17,width=Inf)
### IT IS WORKING-CHECKED

### Save your document
saveRDS(car_data_nov_17,file="C:/Users/USER/Desktop/Data_Analytics/odd_retail_sales_2017_11.rds")

car_data_nov_17 %>% 
  filter(auto_total > 0 & comm_total > 0) %>%
  select(brand_name,total_total) %>%
  arrange(desc(total_total))



##### I would like to see a list of total sales of brands with both automobile and commercial vehicle which are starts with "M" and "V" letter, ordered in decreasing total sales.
car_data_nov_17 %>% 
  filter(auto_total > 100 & comm_total > 100) %>%
  select(starts_with("M") | starts_with("V")) %>%
  arrange(desc(total_total))




